from __future__ import annotations
from argparse import ArgumentParser
from datetime import datetime
from pathlib import Path
from typing import Any
import yaml

SKIP_DIRS = {
    ".git",
    "__pycache__",
    ".venv",
    ".venv-evo2",
    ".venv-boltz2",
    "venv",
    "env",
    "logs",
    "data",
}


def load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as fp:
        return yaml.safe_load(fp) or {}


def list_tree(root: Path, max_depth: int = 2) -> list[str]:
    lines: list[str] = []

    def walk(current: Path, depth: int) -> None:
        if depth > max_depth:
            return
        children = sorted(
            current.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower())
        )
        for child in children:
            if child.name in SKIP_DIRS:
                continue
            rel = child.relative_to(root).as_posix()
            indent = "  " * depth
            suffix = "/" if child.is_dir() else ""
            lines.append(f"{indent}- {rel}{suffix}")
            if child.is_dir():
                walk(child, depth + 1)

    walk(root, 0)
    return lines


def summarize_target_genes(config: dict[str, Any]) -> list[str]:
    genes = config.get("target_genes", []) or []
    rows: list[str] = []
    for item in genes:
        gene = str(item.get("gene", ""))
        logic_type = str(item.get("logic_type", ""))
        scenario = str(item.get("scenario", ""))
        pathway_group = item.get("pathway_group")
        pathway_text = str(pathway_group) if pathway_group else "-"
        rows.append(f"| {gene} | {logic_type} | {scenario} | {pathway_text} |")
    return rows


def build_markdown(root: Path, config: dict[str, Any]) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    paths_cfg = config.get("paths", {}) or {}
    model_cfg = config.get("models", {}) or {}
    pipeline_cfg = config.get("pipeline", {}) or {}
    evo_cfg = pipeline_cfg.get("evo", {}) or {}
    boltz_cfg = pipeline_cfg.get("boltz", {}) or {}
    tree_lines = list_tree(root)
    gene_rows = summarize_target_genes(config)
    main_cmd = "python main.py --stage all"
    init_cmd = "python scripts/init_project.py"
    build_context_cmd = "python scripts/build_project_context.py"
    text = f"# Project Context\n\n> Auto-generated by `scripts/build_project_context.py`.\n> Last updated: {now}\n\n## 1. Project Purpose\n\nAMR-Hunter uses Evo2 (sequence fitness) and Boltz-2 (structure-related metrics) to evaluate mutation impact for AMR analysis.\n\n## 2. Pipeline Contract\n\n1. `init`: Generate mutation tasks from reference genome and write `PENDING` into SQLite.\n2. `evo`: Score mutations, compute `evo_delta`, and split into `BOLTZ_READY` / `LOSS_OF_FUNCTION` / `LETHAL_SKIP`.\n3. `boltz`: Run structure simulation only for `status='BOLTZ_READY'` and `region_type='CDS'`.\n4. `analyze`: Apply pathway + synergy corrections and export CSV.\n\n## 3. Runtime Commands\n\n```bash\n{init_cmd}\n{main_cmd}\n{build_context_cmd}\n```\n\nContainer commander:\n\n```bash\ndocker compose run --rm amr-app --stage all --evo-model auto\n```\n\n## 4. Key Paths (From Config)\n\n- local_db_path: `{paths_cfg.get('local_db_path', '')}`\n- share_db_path: `{paths_cfg.get('share_db_path', '')}`\n- export_csv_path: `{pipeline_cfg.get('export_csv_path', '')}`\n- log_path: `{pipeline_cfg.get('log_path', '')}`\n- metrics_path: `{pipeline_cfg.get('metrics_path', '')}`\n\n## 5. Model Endpoints\n\n- evo2.base_url: `{(model_cfg.get('evo2', {}) or {}).get('base_url', '')}`\n- boltz2.base_url: `{(model_cfg.get('boltz2', {}) or {}).get('base_url', '')}`\n\n## 6. Stage Threshold Snapshot\n\n- evo.lethal_threshold: `{evo_cfg.get('lethal_threshold', '')}`\n- evo.collapse_threshold: `{evo_cfg.get('collapse_threshold', '')}`\n- evo.batch_size/workers: `{evo_cfg.get('batch_size', '')}` / `{evo_cfg.get('workers', '')}`\n- boltz.batch_size/workers: `{boltz_cfg.get('batch_size', '')}` / `{boltz_cfg.get('workers', '')}`\n\n## 7. Target Gene Matrix\n\n| Gene | Logic Type | Scenario | Pathway Group |\n|---|---|---|---|\n{(chr(10).join(gene_rows) if gene_rows else '| - | - | - | - |')}\n\n## 8. Mutation Status Values\n\n`PENDING`, `EVO_DONE`, `BOLTZ_READY`, `LETHAL_SKIP`, `LOSS_OF_FUNCTION`, `COMPLETED`, `RE_SENSITIZED`, `FAILED`\n\n## 9. Code Generation Guardrails\n\n1. Keep stage boundaries stable: Evo must not call Boltz directly.\n2. Preserve `BOLTZ_READY + CDS` filtering for structure stage.\n3. Keep noncoding mutations (`REGULATORY`) out of Boltz stage.\n4. Do not rename existing DB status values without migration.\n5. Keep config-driven behavior in `config/config.yaml`, avoid hardcoding paths.\n\n## 10. Important Files\n\n- `main.py`: stage orchestrator (`--stage evo|boltz|analyze|all`)\n- `auto_run.py`: container commander and model isolation runtime config\n- `scripts/init_project.py`: initialization and mutation generation\n- `core/database.py`: schema, migration, status constraints, db sync\n- `core/clients.py`: Evo2/Boltz2 client and payload building\n- `core/analyzer.py`: filtering + epistasis + synergy\n- `core/generator.py`: mutagenesis engine\n- `config/config.yaml`: single source of truth for pipeline behavior\n\n## 11. Workspace Snapshot (Depth <= 2, filtered)\n\n{(chr(10).join(tree_lines) if tree_lines else '- (empty)')}\n\n## 12. Refresh Policy\n\n- Refresh after changing any of: `config/config.yaml`, `main.py`, `auto_run.py`, `core/*.py`, `scripts/init_project.py`.\n- Command: `python scripts/build_project_context.py`\n"
    return text


def parse_args() -> Any:
    parser = ArgumentParser(
        description="Build Project Context.md from workspace and config"
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "config" / "config.yaml",
        help="Path to config YAML",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "Project Context.md",
        help="Output markdown file path",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    config = load_yaml(args.config)
    content = build_markdown(repo_root, config)
    args.output.write_text(content, encoding="utf-8")
    print(f"Generated: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
